---
title: "simplesim"
format:
  html:
    df-print: paged
---

```{r}
#| output: false
library(tidyverse)
library(magrittr)
library(broom)
library(broom.mixed)
library(brms)
library(rethinking)
library(bayesplot)
library(marginaleffects)

theme_set(theme_bw())
options(
  mc.cores = parallel::detectCores(),
  brms.backend = "cmdstanr"
)

set.seed(19780503)
```

```{r}
n = 10
x = sort(runif(n, min = 0, max = 100))
```

```{r}
true_alpha = 5
true_beta = 2
true_sigma = 10

y = true_alpha + true_beta * x + rnorm(n, mean = 0, sd = true_sigma)

(dat = tibble(x = x, y = y))
```

```{r}
#| message: FALSE
ggplot(dat, aes(x = x, y = y)) + geom_point() + geom_smooth(method = "lm", se = FALSE)
```

```{r}
ff = lm(y ~ x, dat)
```

```{r}
tidy(ff, conf.int = TRUE)
```

```{r}
predictions(ff) %>% tibble
```

```{r}
#| output: false
bf = brm(y ~ x, dat)
```
```{r}
mcmc_trace(bf)
```

```{r}
tidy(bf)
```

```{r}
mcmc_intervals(bf)
```

```{r}
#| output: false
rt = ulam(alist(
  y ~ dnorm(mu, sigma),
  mu <- alpha + beta * x,
  alpha ~ dnorm(0, 100),
  beta ~ dnorm(0, 100),
  sigma ~ dhalfnorm(0, 10)
  ), data = dat, chains=4, cores=4)
```
```{r}
trankplot(rt)
```

```{r}
precis(rt)
```

```{r}
coeftab_plot(coeftab(rt))
```