---
title: "Introduction to probability theory"
format: html
---

## Random variables

-   A random variable is defined as a variable whose numeric value depends on the outcome of a random experiment.

-   A random variable ($X$) associates a value (a real number $x \in \mathbb{R}$) to every possible outcome ($\omega$ in the sample space $\Omega = \{ \omega_1, \omega_2, \ldots, \omega_n \}$) of a random experiment.

-   A random variable is a function from the sample space to the real numbers.

-   A random variable is a function that takes the outcome of a random experiment as input and returns a real number as output, for example:

$$
X(\omega_1) = 5
$$

-   A random variable often describes a measurable quantity associated with the outcome of random experiment or it indicates whether an event ($A$) has occurred (e.g., $x = 1$ if $\omega_1 \in A$ or $x = 0$ if $\omega_1 \notin A$).

-   One or more random variables can be defined on the same sample space.

-   A function of one or more random variables is also a random variable.

## Probability mass function (PMF) or a discrete r.v.

-   The PMF is the "probability law" or "probability distribution" of $X$.

-   If $x$ is fixed (e.g., $x = 5$) then $X = x$ (i.e., $X = 5$) is an event (a subset of the sample space $\Omega = \{ \omega_1, \omega_2, \ldots, \omega_n \}$):

$$
\{\omega \in \Omega: X(\omega) = 5 \}
$$

-   $p_X(x) = P(X = x) = P(\{ \omega \in \Omega : X(\omega) = x \})$
-   $p_X(x) \ge 0$
-   $\sum_x p_X(x) = 1$
